# Meta opts:
## preprocess:
save_data: generated/sharded.ex0
overwrite: False

### vocab:
src_vocab: examples/subword_share/efcjk_shared_50k.spm-onmt_dynamic.vocab
src_vocab_size: 60000
tgt_vocab_size: 60000
vocab_size_multiple: 8
src_words_min_frequency: 10
tgt_words_min_frequency: 10
share_vocab: True
### Transform related opts:
src_subword_type: sentencepiece
tgt_subword_type: sentencepiece
src_subword_model: examples/subword_share/efcjk_shared_50k.en-fr-zh-ja-ko.spm.model
tgt_subword_model: examples/subword_share/efcjk_shared_50k.en-fr-zh-ja-ko.spm.model
n_samples_subword: 4
theta_subword: 0.5
switchout_temperature: 1
worddrop_temperature: 2
src_seq_length: 300
tgt_seq_length: 300

# Corpus opts:
data:
    corpus_1:
        path_src: data/src-train.txt
        path_tgt: data/tgt-train.txt
        transforms: [switchout, sentencepiece, prefix, filtertoolong]
        weight: 5
        src_lang: en
        tgt_lang: fr
    valid:
        path_src: data/src-val.txt
        path_tgt: data/tgt-val.txt
        transforms: [sentencepiece, prefix]
        src_lang: en
        tgt_lang: fr
